local LSM = LibStub("LibSharedMedia-3.0")
LSM:Register("statusbar", "dN", [[Interface\Addons\RaccoonUI\textures\dN.tga]])
LSM:Register("statusbar", "dP", [[Interface\Addons\RaccoonUI\textures\dP.tga]])
LSM:Register("statusbar", "dU", [[Interface\Addons\RaccoonUI\textures\dU.tga]])
LSM:Register("statusbar", "Hal U", [[Interface\Addons\RaccoonUI\textures\HalU.tga]])
LSM:Register("statusbar", "Skewed", [[Interface\Addons\RaccoonUI\textures\Skewed.tga]])
LSM:Register("statusbar", "Skewed Inverted", [[Interface\Addons\RaccoonUI\textures\Skewed_Inverted]])
LSM:Register("statusbar", "DsmV1", [[Interface\Addons\RaccoonUI\textures\DsmV1]])
